name: Build Vue
on: [push]

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'gonzasestopal'
        reponame: 'coffee-app'
        token: ${{ secrets.GITHUB_TOKEN }}
